// Local adapter: no network requests.
function XrServer_initial(){return OfflineGame.serverUnavailable();}
function XrServer_captcha(){return OfflineGame.serverUnavailable();}
function XrServer_login(){return OfflineGame.serverUnavailable();}
function XrServer_Lud(){return OfflineGame.serverUnavailable();}
function XrServer_Ulg(){return OfflineGame.serverUnavailable();}
function XrServer_signup(){return OfflineGame.serverUnavailable();}
function XrServer_Usc(){return OfflineGame.serverUnavailable();}
function XrServer_Dsc(){return OfflineGame.serverUnavailable();}
function XrServer_Ngi(){return OfflineGame.serverUnavailable();}
function XrServer_Fgi(){return OfflineGame.serverUnavailable();}
function XrServer_Wgi(){return OfflineGame.serverUnavailable();}
function XrServer_TP(){return OfflineGame.serverUnavailable();}
function XrServer_ZXLW(){return OfflineGame.serverUnavailable();}
function XrServer_Getl(){return OfflineGame.serverUnavailable();}
function XrServer_Gwtl(){return OfflineGame.serverUnavailable();}
function XrServer_Gatl(){return OfflineGame.serverUnavailable();}
function XrServer_Ghtl(){return OfflineGame.serverUnavailable();}
function XrServer_Grtl(){return OfflineGame.serverUnavailable();}