/* Original NPC encounters for Tàn Đăng Vấn Đạo. Uses the existing annual choices. */
(function(){
'use strict';
var roster=[
 {id:'moc_nuong',name:'Mộc Nương',age:121,realm:'Nguyên Anh',role:'Người dẫn đạo',place:'Bến Vô Sinh',text:'Bà lão đặt mái chèo xuống, nghe ngươi kể những giấc mộng sau khi dẫn khí. “Sống lâu không khó bằng nhớ vì sao mình muốn sống,” bà nói.',help:'Chèo thuyền đưa khách qua bến',result:'Ngươi giữ thuyền qua dòng nước xoáy. Mộc Nương chỉ cách giữ tâm khi linh khí nghịch chuyển.',qi:18,stones:8,lesson:'Học Tĩnh Tâm Thiên',cost:12,lessonQi:38,quest:'Thắp lại bảy đèn dẫn lối',reward:'Mộc Nương trao pháp môn Hộ Tâm Đăng.',param:1,amount:2000},
 {id:'a_tich',name:'A Tịch',age:125,realm:'Luyện Khí',role:'Người đưa tin',place:'Bến Vô Sinh',text:'A Tịch ngồi bên những phong thư chưa tìm được người nhận. Cậu nhờ ngươi đối chiếu các địa danh cũ để người đã đi xa không bị quên tên.',help:'Cùng tìm người nhận thư',result:'Một lá thư tới được tay hậu nhân. A Tịch ghi lại đường đi cho ngươi; một mối nhân duyên được nối lại.',qi:16,stones:14,lesson:'Mua bản đồ linh tuyền',cost:10,lessonQi:32,quest:'Trao thư cuối của thành Lưu Quang',reward:'A Tịch tìm được linh tuyền nuôi dưỡng thân thể để trả ơn.',param:0,amount:5000},
 {id:'khuong_hoai',name:'Khương Hoài',age:135,realm:'Kim Đan',role:'Chưởng viện trận pháp',place:'Thanh Khuyết Sơn',text:'Chưởng viện trải trận đồ lên bàn đá. Ông không hỏi tuổi ngươi, chỉ hỏi một linh mạch nên nuôi người trong núi hay cả những làng dưới chân núi.',help:'Sửa nhánh trận dẫn nước xuống làng',result:'Ngươi nhận ra một dòng linh khí bị khóa dưới lòng đất. Khương Hoài ghi nhận lời giải, dù vẫn chưa đồng ý cách phân chia của ngươi.',qi:22,stones:10,lesson:'Nghiên cứu chú giải trận pháp',cost:18,lessonQi:48,quest:'Hoàn chỉnh trận đồ hai nhánh',reward:'Khương Hoài trao một phần truyền thừa Ngưng Mạch.',param:1,amount:3000},
 {id:'diep_thanh_la',name:'Diệp Thanh La',age:140,realm:'Trúc Cơ',role:'Đan sư',place:'Dược Cốc',text:'Nữ đan sư đang cứu một con linh thú trúng độc. Nàng chỉ bán đan có ghi rõ dược tính, không bán thứ thuốc được quảng cáo là trường sinh.',help:'Thu thập linh thảo cho Dược Cốc',result:'Ngươi học cách phân biệt linh thảo và độc thảo. Thanh La chia phần linh thạch từ mẻ dược vừa hoàn thành.',qi:18,stones:16,lesson:'Mua Ngưng Khí Đan',cost:20,lessonQi:55,quest:'Khôi phục vườn Bạch Lộ',reward:'Thanh La luyện Tẩy Tủy Đan, giúp thân thể ngươi bền bỉ hơn.',param:0,amount:8000},
 {id:'bach_luyen',name:'Bách Luyện',age:160,realm:'Kim Đan',role:'Luyện khí sư',place:'Lò Vân Thiết',text:'Lão thợ rèn nhìn vũ khí của ngươi trước khi nhìn cảnh giới. “Đồ tốt phải chịu được tay người dùng,” lão nói rồi kéo bễ lò.',help:'Giữ lửa luyện linh thiết',result:'Ngươi điều hòa linh khí theo nhịp búa. Bách Luyện trả công bằng linh thạch và chỉ ra điểm hao lực trong cách vận công.',qi:20,stones:18,lesson:'Học cách dẫn khí vào vũ khí',cost:22,lessonQi:58,quest:'Rèn hoàn chỉnh phôi Vân Thiết',reward:'Bách Luyện truyền kỹ thuật vận lực qua binh khí.',param:2,amount:1500},
 {id:'ta_vo_tran',name:'Tạ Vô Trần',age:180,realm:'Nguyên Anh',role:'Kiếm tu vân du',place:'Đỉnh Tịch Phong',text:'Kiếm khách dùng một nhành trúc vạch đường trên tuyết. Hắn mời ngươi luyện thế, thu kiếm trước khi chạm người; đây là chỉ điểm, không phải cuộc đấu sinh tử.',help:'Luyện thế kiếm đến bình minh',result:'Qua hàng trăm lần sửa bộ pháp, ngươi hiểu thêm cách để nội lực đi trước lưỡi kiếm.',qi:28,stones:6,lesson:'Xin chỉ điểm kiếm ý',cost:25,lessonQi:65,quest:'Giữ một thế kiếm giữa gió núi',reward:'Tạ Vô Trần truyền kiếm ý Phong Tức, tăng công kích thực.',param:2,amount:2500},
 {id:'huyen_nha',name:'Huyền Nha',age:220,realm:'Kim Đan',role:'Thương nhân bí cảnh',place:'Chợ Đêm Vô Nguyệt',text:'Thương nhân đeo mặt nạ đặt ba chiếc hộp niêm phong lên bàn. Ngươi yêu cầu hắn mở hộp kiểm hàng trước khi bàn giá; hắn bật cười rồi làm theo.',help:'Hộ tống hàng qua đường núi',result:'Chuyến hàng đến đủ. Huyền Nha trả đúng giá đã hẹn, đồng thời bán cho ngươi một tin tức không kèm lời thề mơ hồ.',qi:20,stones:25,lesson:'Mua tàn quyển đã kiểm chứng',cost:30,lessonQi:75,quest:'Tìm lại sổ đường vào bí cảnh',reward:'Tàn quyển hoàn chỉnh giúp ngươi mở rộng khí hải.',param:1,amount:4000},
 {id:'van_chi',name:'Vân Chi',age:300,realm:'Hóa Thần',role:'Người giữ linh mạch',place:'Vườn Không Trăng',text:'Người giữ vườn không mang pháp khí. Nàng đặt tay lên đất, chỉ cho ngươi nghe tiếng linh mạch đang yếu dần dưới những trận hút khí.',help:'Chăm sóc một nhánh linh mạch',result:'Ngươi dẫn linh khí về rễ cây thay vì giữ lại cho riêng mình. Vân Chi chỉ cho ngươi một nhánh mạch đã tự hồi phục.',qi:32,stones:14,lesson:'Học phép dưỡng mạch',cost:35,lessonQi:90,quest:'Hồi sinh mầm cây Lưu Quang',reward:'Vân Chi trao giọt linh lộ kết từ nhánh mạch đã cứu.',param:0,amount:12000}
];
function data(s,id){s.npcs=s.npcs||{};return s.npcs[id]||(s.npcs[id]={relation:0,helped:0,questDone:false,visits:0});}
function offer(age,s){
 // Interleave NPCs with the existing exploration events; story and breakthroughs take priority.
 if(age%2===0)return null;
 var eligible=roster.filter(function(n){return age>=n.age;}),n=eligible[Math.floor((age-121)/2)%eligible.length];if(!n)return null;
 var d=data(s,n.id),choices=[
 {label:n.help,text:n.result,qi:n.qi,stones:n.stones,heart:1,npc:n.id,npcAction:'help'},
 {label:n.lesson+' ('+n.cost+' linh thạch)',text:n.name+' giải thích từng bước để ngươi tự luyện, không ép ngươi dùng phương pháp vượt cảnh giới.',qi:n.lessonQi,stones:-n.cost,cost:n.cost,npc:n.id,npcAction:'learn'}
 ];
 if(d.helped>=3&&!d.questDone)choices.push({label:n.quest,text:n.reward+' +'+n.amount+' '+['máu tối đa','nội lực tối đa','công kích'][n.param]+'.',qi:50,stones:20,heart:2,npc:n.id,npcAction:'quest'});
 return {title:n.name+' — '+n.role,text:n.place+' · '+n.realm+'. '+n.text+' Quan hệ: '+d.relation+'. Đã giúp: '+d.helped+'/3.'+(d.questDone?' Nhiệm vụ riêng đã hoàn thành.':' Giúp đỡ ba lần để mở nhiệm vụ riêng.'),choices:choices};
}
function valid(s,c){if(!c.npc)return true;var n=roster.filter(function(n){return n.id===c.npc;})[0];if(!n)return false;var d=data(s,n.id);return c.npcAction!=='quest'||(d.helped>=3&&!d.questDone);}
function apply(s,c){if(!c.npc)return;var n=roster.filter(function(n){return n.id===c.npc;})[0],d=data(s,n.id);d.visits++;d.relation+=c.npcAction==='help'?2:1;
 if(c.npcAction==='help')d.helped++;
 if(c.npcAction==='quest'){d.questDone=true;s.bonus[n.param]+=n.amount;}
}
window.WebImmortalNPC={roster:roster,offer:offer,valid:valid,apply:apply};
}());
